<?php

use App\Models\Language;

use Illuminate\Database\Seeder;

class languageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        
        // DB::table('languages')->delete();
        // Language::create(['code' => 'ace', 'name' => 'Achinese',               'script' => 'Latn', 'native' => 'Aceh', 'regional' =>  '',  'direction' => 'ltr', 'active' => 0, 'country' => '', 'country' => '']);
        // Language::create(['code' => 'af', 'name' => 'Afrikaans',              'script' => 'Latn', 'native' => 'Afrikaans', 'regional' => 'af_ZA', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'agq', 'name' => 'Aghem',                  'script' => 'Latn', 'native' => 'Aghem', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'ak', 'name' => 'Akan',                   'script' => 'Latn', 'native' => 'Akan', 'regional' => 'ak_GH', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'an', 'name' => 'Aragonese',              'script' => 'Latn', 'native' => 'aragonés', 'regional' => 'an_ES', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'cch', 'name' => 'Atsam',                  'script' => 'Latn', 'native' => 'Atsam', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'gn', 'name' => 'Guaraní',                'script' => 'Latn', 'native' => 'Avañe’ẽ', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'ae', 'name' => 'Avestan',                'script' => 'Latn', 'native' => 'avesta', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'ay', 'name' => 'Aymara',                 'script' => 'Latn', 'native' => 'aymar aru', 'regional' => 'ay_PE', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'az', 'name' => 'Azerbaijani (Latin)',    'script' => 'Latn', 'native' => 'azərbaycanca', 'regional' => 'az_AZ', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'id', 'name' => 'Indonesian',             'script' => 'Latn', 'native' => 'Bahasa Indonesia', 'regional' => 'id_ID', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'ms', 'name' => 'Malay',                  'script' => 'Latn', 'native' => 'Bahasa Melayu', 'regional' => 'ms_MY', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'bm', 'name' => 'Bambara',                'script' => 'Latn', 'native' => 'bamanakan', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'jv', 'name' => 'Javanese (Latin)',       'script' => 'Latn', 'native' => 'Basa Jawa', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'su', 'name' => 'Sundanese',              'script' => 'Latn', 'native' => 'Basa Sunda', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'bh', 'name' => 'Bihari',                 'script' => 'Latn', 'native' => 'Bihari', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'bi', 'name' => 'Bislama',                'script' => 'Latn', 'native' => 'Bislama', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'nb', 'name' => 'Norwegian Bokmål',       'script' => 'Latn', 'native' => 'Bokmål', 'regional' => 'nb_NO', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'bs', 'name' => 'Bosnian',                'script' => 'Latn', 'native' => 'bosanski', 'regional' => 'bs_BA', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'br', 'name' => 'Breton',                 'script' => 'Latn', 'native' => 'brezhoneg', 'regional' => 'br_FR', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'ca', 'name' => 'Catalan',                'script' => 'Latn', 'native' => 'català', 'regional' => 'ca_ES', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'ch', 'name' => 'Chamorro',               'script' => 'Latn', 'native' => 'Chamoru', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'ny', 'name' => 'Chewa',                  'script' => 'Latn', 'native' => 'chiCheŵa', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'kde', 'name' => 'Makonde',                'script' => 'Latn', 'native' => 'Chimakonde', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'sn', 'name' => 'Shona',                  'script' => 'Latn', 'native' => 'chiShona', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'co', 'name' => 'Corsican',               'script' => 'Latn', 'native' => 'corsu', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'cy', 'name' => 'Welsh',                  'script' => 'Latn', 'native' => 'Cymraeg', 'regional' => 'cy_GB', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'da', 'name' => 'Danish',                 'script' => 'Latn', 'native' => 'dansk', 'regional' => 'da_DK', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'se', 'name' => 'Northern Sami',          'script' => 'Latn', 'native' => 'davvisámegiella', 'regional' => 'se_NO', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'de', 'name' => 'German',                 'script' => 'Latn', 'native' => 'Deutsch', 'regional' => 'de_DE', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'luo', 'name' => 'Luo',                    'script' => 'Latn', 'native' => 'Dholuo', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'nv', 'name' => 'Navajo',                 'script' => 'Latn', 'native' => 'Diné bizaad', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'dua', 'name' => 'Duala',                  'script' => 'Latn', 'native' => 'duálá', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'et', 'name' => 'Estonian',               'script' => 'Latn', 'native' => 'eesti', 'regional' => 'et_EE', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'na', 'name' => 'Nauru',                  'script' => 'Latn', 'native' => 'Ekakairũ Naoero', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'guz', 'name' => 'Ekegusii',               'script' => 'Latn', 'native' => 'Ekegusii', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        Language::create(['code' => 'en', 'name' => 'English',                'script' => 'Latn', 'native' => 'English', 'regional' => 'en_GB', 'direction' => 'ltr', 'active' => 1, 'country' => '']);
        // Language::create(['code' => 'en-AU', 'name' => 'Australian English',     'script' => 'Latn', 'native' => 'Australian English', 'regional' => 'en_AU', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'en-GB', 'name' => 'British English',        'script' => 'Latn', 'native' => 'British English', 'regional' => 'en_GB', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'en-CA', 'name' => 'Canadian English',       'script' => 'Latn', 'native' => 'Canadian English', 'regional' => 'en_CA', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'en-US', 'name' => 'U.S. English',           'script' => 'Latn', 'native' => 'U.S. English', 'regional' => 'en_US', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'es', 'name' => 'Spanish',                'script' => 'Latn', 'native' => 'español', 'regional' => 'es_ES', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'eo', 'name' => 'Esperanto',              'script' => 'Latn', 'native' => 'esperanto', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'eu', 'name' => 'Basque',                 'script' => 'Latn', 'native' => 'euskara', 'regional' => 'eu_ES', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'ewo', 'name' => 'Ewondo',                 'script' => 'Latn', 'native' => 'ewondo', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'ee', 'name' => 'Ewe',                    'script' => 'Latn', 'native' => 'eʋegbe', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'fil', 'name' => 'Filipino',               'script' => 'Latn', 'native' => 'Filipino', 'regional' => 'fil_PH', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'fr', 'name' => 'French',                 'script' => 'Latn', 'native' => 'français', 'regional' => 'fr_FR', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'fr-CA', 'name' => 'Canadian French',        'script' => 'Latn', 'native' => 'français canadien', 'regional' => 'fr_CA', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'fy', 'name' => 'Western Frisian',        'script' => 'Latn', 'native' => 'frysk', 'regional' => 'fy_DE', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'fur', 'name' => 'Friulian',               'script' => 'Latn', 'native' => 'furlan', 'regional' => 'fur_IT', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'fo', 'name' => 'Faroese',                'script' => 'Latn', 'native' => 'føroyskt', 'regional' => 'fo_FO', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'gaa', 'name' => 'Ga',                     'script' => 'Latn', 'native' => 'Ga', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'ga', 'name' => 'Irish',                  'script' => 'Latn', 'native' => 'Gaeilge', 'regional' => 'ga_IE', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'gv', 'name' => 'Manx',                   'script' => 'Latn', 'native' => 'Gaelg', 'regional' => 'gv_GB', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'sm', 'name' => 'Samoan',                 'script' => 'Latn', 'native' => 'Gagana fa’a Sāmoa', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'gl', 'name' => 'Galician',               'script' => 'Latn', 'native' => 'galego', 'regional' => 'gl_ES', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'ki', 'name' => 'Kikuyu',                 'script' => 'Latn', 'native' => 'Gikuyu', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'gd', 'name' => 'Scottish Gaelic',        'script' => 'Latn', 'native' => 'Gàidhlig', 'regional' => 'gd_GB', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'ha', 'name' => 'Hausa',                  'script' => 'Latn', 'native' => 'Hausa', 'regional' => 'ha_NG', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'bez', 'name' => 'Bena',                   'script' => 'Latn', 'native' => 'Hibena', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'ho', 'name' => 'Hiri Motu',              'script' => 'Latn', 'native' => 'Hiri Motu', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'hr', 'name' => 'Croatian',               'script' => 'Latn', 'native' => 'hrvatski', 'regional' => 'hr_HR', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'bem', 'name' => 'Bemba',                  'script' => 'Latn', 'native' => 'Ichibemba', 'regional' => 'bem_ZM', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'io', 'name' => 'Ido',                    'script' => 'Latn', 'native' => 'Ido', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'ig', 'name' => 'Igbo',                   'script' => 'Latn', 'native' => 'Igbo', 'regional' => 'ig_NG', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'rn', 'name' => 'Rundi',                  'script' => 'Latn', 'native' => 'Ikirundi', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'ia', 'name' => 'Interlingua',            'script' => 'Latn', 'native' => 'interlingua', 'regional' => 'ia_FR', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'iu-Latn', 'name' => 'Inuktitut (Latin)',      'script' => 'Latn', 'native' => 'Inuktitut', 'regional' => 'iu_CA', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'sbp', 'name' => 'Sileibi',                'script' => 'Latn', 'native' => 'Ishisangu', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'nd', 'name' => 'North Ndebele',          'script' => 'Latn', 'native' => 'isiNdebele', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'nr', 'name' => 'South Ndebele',          'script' => 'Latn', 'native' => 'isiNdebele', 'regional' => 'nr_ZA', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'xh', 'name' => 'Xhosa',                  'script' => 'Latn', 'native' => 'isiXhosa', 'regional' => 'xh_ZA', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'zu', 'name' => 'Zulu',                   'script' => 'Latn', 'native' => 'isiZulu', 'regional' => 'zu_ZA', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'it', 'name' => 'Italian',                'script' => 'Latn', 'native' => 'italiano', 'regional' => 'it_IT', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'ik', 'name' => 'Inupiaq',                'script' => 'Latn', 'native' => 'Iñupiaq', 'regional' => 'ik_CA', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'dyo', 'name' => 'Jola-Fonyi',             'script' => 'Latn', 'native' => 'joola', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'kea', 'name' => 'Kabuverdianu',           'script' => 'Latn', 'native' => 'kabuverdianu', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'kaj', 'name' => 'Jju',                    'script' => 'Latn', 'native' => 'Kaje', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'mh', 'name' => 'Marshallese',            'script' => 'Latn', 'native' => 'Kajin M̧ajeļ', 'regional' => 'mh_MH', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'kl', 'name' => 'Kalaallisut',            'script' => 'Latn', 'native' => 'kalaallisut', 'regional' => 'kl_GL', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'kln', 'name' => 'Kalenjin',               'script' => 'Latn', 'native' => 'Kalenjin', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'kr', 'name' => 'Kanuri',                 'script' => 'Latn', 'native' => 'Kanuri', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'kcg', 'name' => 'Tyap',                   'script' => 'Latn', 'native' => 'Katab', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'kw', 'name' => 'Cornish',                'script' => 'Latn', 'native' => 'kernewek', 'regional' => 'kw_GB', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'naq', 'name' => 'Nama',                   'script' => 'Latn', 'native' => 'Khoekhoegowab', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'rof', 'name' => 'Rombo',                  'script' => 'Latn', 'native' => 'Kihorombo', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'kam', 'name' => 'Kamba',                  'script' => 'Latn', 'native' => 'Kikamba', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'kg', 'name' => 'Kongo',                  'script' => 'Latn', 'native' => 'Kikongo', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'jmc', 'name' => 'Machame',                'script' => 'Latn', 'native' => 'Kimachame', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'rw', 'name' => 'Kinyarwanda',            'script' => 'Latn', 'native' => 'Kinyarwanda', 'regional' => 'rw_RW', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'asa', 'name' => 'Kipare',                 'script' => 'Latn', 'native' => 'Kipare', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'rwk', 'name' => 'Rwa',                    'script' => 'Latn', 'native' => 'Kiruwa', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'saq', 'name' => 'Samburu',                'script' => 'Latn', 'native' => 'Kisampur', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'ksb', 'name' => 'Shambala',               'script' => 'Latn', 'native' => 'Kishambaa', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'swc', 'name' => 'Congo Swahili',          'script' => 'Latn', 'native' => 'Kiswahili ya Kongo', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'sw', 'name' => 'Swahili',                'script' => 'Latn', 'native' => 'Kiswahili', 'regional' => 'sw_KE', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'dav', 'name' => 'Dawida',                 'script' => 'Latn', 'native' => 'Kitaita', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'teo', 'name' => 'Teso',                   'script' => 'Latn', 'native' => 'Kiteso', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'khq', 'name' => 'Koyra Chiini',           'script' => 'Latn', 'native' => 'Koyra ciini', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'ses', 'name' => 'Songhay',                'script' => 'Latn', 'native' => 'Koyraboro senni', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'mfe', 'name' => 'Morisyen',               'script' => 'Latn', 'native' => 'kreol morisien', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'ht', 'name' => 'Haitian',                'script' => 'Latn', 'native' => 'Kreyòl ayisyen', 'regional' => 'ht_HT', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'kj', 'name' => 'Kuanyama',               'script' => 'Latn', 'native' => 'Kwanyama', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'ksh', 'name' => 'Kölsch',                 'script' => 'Latn', 'native' => 'Kölsch', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'ebu', 'name' => 'Kiembu',                 'script' => 'Latn', 'native' => 'Kĩembu', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'mer', 'name' => 'Kimîîru',                'script' => 'Latn', 'native' => 'Kĩmĩrũ', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'lag', 'name' => 'Langi',                  'script' => 'Latn', 'native' => 'Kɨlaangi', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'lah', 'name' => 'Lahnda',                 'script' => 'Latn', 'native' => 'Lahnda', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'la', 'name' => 'Latin',                  'script' => 'Latn', 'native' => 'latine', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'lv', 'name' => 'Latvian',                'script' => 'Latn', 'native' => 'latviešu', 'regional' => 'lv_LV', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'to', 'name' => 'Tongan',                 'script' => 'Latn', 'native' => 'lea fakatonga', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'lt', 'name' => 'Lithuanian',             'script' => 'Latn', 'native' => 'lietuvių', 'regional' => 'lt_LT', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'li', 'name' => 'Limburgish',             'script' => 'Latn', 'native' => 'Limburgs', 'regional' => 'li_BE', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'ln', 'name' => 'Lingala',                'script' => 'Latn', 'native' => 'lingála', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'lg', 'name' => 'Ganda',                  'script' => 'Latn', 'native' => 'Luganda', 'regional' => 'lg_UG', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'luy', 'name' => 'Oluluyia',               'script' => 'Latn', 'native' => 'Luluhia', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'lb', 'name' => 'Luxembourgish',          'script' => 'Latn', 'native' => 'Lëtzebuergesch', 'regional' => 'lb_LU', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'hu', 'name' => 'Hungarian',              'script' => 'Latn', 'native' => 'magyar', 'regional' => 'hu_HU', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'mgh', 'name' => 'Makhuwa-Meetto',         'script' => 'Latn', 'native' => 'Makua', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'mg', 'name' => 'Malagasy',               'script' => 'Latn', 'native' => 'Malagasy', 'regional' => 'mg_MG', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'mt', 'name' => 'Maltese',                'script' => 'Latn', 'native' => 'Malti', 'regional' => 'mt_MT', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'mtr', 'name' => 'Mewari',                 'script' => 'Latn', 'native' => 'Mewari', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'mua', 'name' => 'Mundang',                'script' => 'Latn', 'native' => 'Mundang', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'mi', 'name' => 'Māori',                  'script' => 'Latn', 'native' => 'Māori', 'regional' => 'mi_NZ', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'nl', 'name' => 'Dutch',                  'script' => 'Latn', 'native' => 'Nederlands', 'regional' => 'nl_NL', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'nmg', 'name' => 'Kwasio',                 'script' => 'Latn', 'native' => 'ngumba', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'yav', 'name' => 'Yangben',                'script' => 'Latn', 'native' => 'nuasue', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'nn', 'name' => 'Norwegian Nynorsk',      'script' => 'Latn', 'native' => 'nynorsk', 'regional' => 'nn_NO', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'oc', 'name' => 'Occitan',                'script' => 'Latn', 'native' => 'occitan', 'regional' => 'oc_FR', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'ang', 'name' => 'Old English',            'script' => 'Runr', 'native' => 'Old English', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'xog', 'name' => 'Soga',                   'script' => 'Latn', 'native' => 'Olusoga', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'om', 'name' => 'Oromo',                  'script' => 'Latn', 'native' => 'Oromoo', 'regional' => 'om_ET', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'ng', 'name' => 'Ndonga',                 'script' => 'Latn', 'native' => 'OshiNdonga', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'hz', 'name' => 'Herero',                 'script' => 'Latn', 'native' => 'Otjiherero', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'uz-Latn', 'name' => 'Uzbek (Latin)',          'script' => 'Latn', 'native' => 'oʼzbekcha', 'regional' => 'uz_UZ', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'nds', 'name' => 'Low German',             'script' => 'Latn', 'native' => 'Plattdüütsch', 'regional' => 'nds_DE', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'pl', 'name' => 'Polish',                 'script' => 'Latn', 'native' => 'polski', 'regional' => 'pl_PL', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'pt', 'name' => 'Portuguese',             'script' => 'Latn', 'native' => 'português', 'regional' => 'pt_PT', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'pt-BR', 'name' => 'Brazilian Portuguese',   'script' => 'Latn', 'native' => 'português do Brasil', 'regional' => 'pt_BR', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'ff', 'name' => 'Fulah',                  'script' => 'Latn', 'native' => 'Pulaar', 'regional' => 'ff_SN', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'pi', 'name' => 'Pahari-Potwari',         'script' => 'Latn', 'native' => 'Pāli', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'aa', 'name' => 'Afar',                   'script' => 'Latn', 'native' => 'Qafar', 'regional' => 'aa_ER', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'ty', 'name' => 'Tahitian',               'script' => 'Latn', 'native' => 'Reo Māohi', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'ksf', 'name' => 'Bafia',                  'script' => 'Latn', 'native' => 'rikpa', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'ro', 'name' => 'Romanian',               'script' => 'Latn', 'native' => 'română', 'regional' => 'ro_RO', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'cgg', 'name' => 'Chiga',                  'script' => 'Latn', 'native' => 'Rukiga', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'rm', 'name' => 'Romansh',                'script' => 'Latn', 'native' => 'rumantsch', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'qu', 'name' => 'Quechua',                'script' => 'Latn', 'native' => 'Runa Simi', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'nyn', 'name' => 'Nyankole',               'script' => 'Latn', 'native' => 'Runyankore', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'ssy', 'name' => 'Saho',                   'script' => 'Latn', 'native' => 'Saho', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'sc', 'name' => 'Sardinian',              'script' => 'Latn', 'native' => 'sardu', 'regional' => 'sc_IT', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'de-CH', 'name' => 'Swiss High German',      'script' => 'Latn', 'native' => 'Schweizer Hochdeutsch', 'regional' => 'de_CH', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'gsw', 'name' => 'Swiss German',           'script' => 'Latn', 'native' => 'Schwiizertüütsch', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'trv', 'name' => 'Taroko',                 'script' => 'Latn', 'native' => 'Seediq', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'seh', 'name' => 'Sena',                   'script' => 'Latn', 'native' => 'sena', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'nso', 'name' => 'Northern Sotho',         'script' => 'Latn', 'native' => 'Sesotho sa Leboa', 'regional' => 'nso_ZA', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'st', 'name' => 'Southern Sotho',         'script' => 'Latn', 'native' => 'Sesotho', 'regional' => 'st_ZA', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'tn', 'name' => 'Tswana',                 'script' => 'Latn', 'native' => 'Setswana', 'regional' => 'tn_ZA', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'sq', 'name' => 'Albanian',               'script' => 'Latn', 'native' => 'shqip', 'regional' => 'sq_AL', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'sid', 'name' => 'Sidamo',                 'script' => 'Latn', 'native' => 'Sidaamu Afo', 'regional' => 'sid_ET', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'ss', 'name' => 'Swati',                  'script' => 'Latn', 'native' => 'Siswati', 'regional' => 'ss_ZA', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'sk', 'name' => 'Slovak',                 'script' => 'Latn', 'native' => 'slovenčina', 'regional' => 'sk_SK', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'sl', 'name' => 'Slovene',                'script' => 'Latn', 'native' => 'slovenščina', 'regional' => 'sl_SI', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'so', 'name' => 'Somali',                 'script' => 'Latn', 'native' => 'Soomaali', 'regional' => 'so_SO', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'sr-Latn', 'name' => 'Serbian (Latin)',        'script' => 'Latn', 'native' => 'Srpski', 'regional' => 'sr_RS', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'sh', 'name' => 'Serbo-Croatian',         'script' => 'Latn', 'native' => 'srpskohrvatski', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'fi', 'name' => 'Finnish',                'script' => 'Latn', 'native' => 'suomi', 'regional' => 'fi_FI', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'sv', 'name' => 'Swedish',                'script' => 'Latn', 'native' => 'svenska', 'regional' => 'sv_SE', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'sg', 'name' => 'Sango',                  'script' => 'Latn', 'native' => 'Sängö', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'tl', 'name' => 'Tagalog',                'script' => 'Latn', 'native' => 'Tagalog', 'regional' => 'tl_PH', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'tzm-Latn', 'name' => 'Central Atlas Tamazight (Latin)', 'script' => 'Latn', 'native' => 'Tamazight', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'kab', 'name' => 'Kabyle',                 'script' => 'Latn', 'native' => 'Taqbaylit', 'regional' => 'kab_DZ', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'twq', 'name' => 'Tasawaq',                'script' => 'Latn', 'native' => 'Tasawaq senni', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'shi', 'name' => 'Tachelhit (Latin)',      'script' => 'Latn', 'native' => 'Tashelhit', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'nus', 'name' => 'Nuer',                   'script' => 'Latn', 'native' => 'Thok Nath', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'vi', 'name' => 'Vietnamese',             'script' => 'Latn', 'native' => 'Tiếng Việt', 'regional' => 'vi_VN', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'tg-Latn', 'name' => 'Tajik (Latin)',          'script' => 'Latn', 'native' => 'tojikī', 'regional' => 'tg_TJ', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'lu', 'name' => 'Luba-Katanga',           'script' => 'Latn', 'native' => 'Tshiluba', 'regional' => 've_ZA', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 've', 'name' => 'Venda',                  'script' => 'Latn', 'native' => 'Tshivenḓa', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'tw', 'name' => 'Twi',                    'script' => 'Latn', 'native' => 'Twi', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'tr', 'name' => 'Turkish',                'script' => 'Latn', 'native' => 'Türkçe', 'regional' => 'tr_TR', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'ale', 'name' => 'Aleut',                  'script' => 'Latn', 'native' => 'Unangax tunuu', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'ca-valencia', 'name' => 'Valencian',              'script' => 'Latn', 'native' => 'valencià', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'vai-Latn', 'name' => 'Vai (Latin)',            'script' => 'Latn', 'native' => 'Viyamíĩ', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'vo', 'name' => 'Volapük',                'script' => 'Latn', 'native' => 'Volapük', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'fj', 'name' => 'Fijian',                 'script' => 'Latn', 'native' => 'vosa Vakaviti', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'wa', 'name' => 'Walloon',                'script' => 'Latn', 'native' => 'Walon', 'regional' => 'wa_BE', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'wae', 'name' => 'Walser',                 'script' => 'Latn', 'native' => 'Walser', 'regional' => 'wae_CH', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'wen', 'name' => 'Sorbian',                'script' => 'Latn', 'native' => 'Wendic', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'wo', 'name' => 'Wolof',                  'script' => 'Latn', 'native' => 'Wolof', 'regional' => 'wo_SN', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'ts', 'name' => 'Tsonga',                 'script' => 'Latn', 'native' => 'Xitsonga', 'regional' => 'ts_ZA', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'dje', 'name' => 'Zarma',                  'script' => 'Latn', 'native' => 'Zarmaciine', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'yo', 'name' => 'Yoruba',                 'script' => 'Latn', 'native' => 'Èdè Yorùbá', 'regional' => 'yo_NG', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'de-AT', 'name' => 'Austrian German',        'script' => 'Latn', 'native' => 'Österreichisches Deutsch', 'regional' => 'de_AT', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'is', 'name' => 'Icelandic',              'script' => 'Latn', 'native' => 'íslenska', 'regional' => 'is_IS', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'cs', 'name' => 'Czech',                  'script' => 'Latn', 'native' => 'čeština', 'regional' => 'cs_CZ', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'bas', 'name' => 'Basa',                   'script' => 'Latn', 'native' => 'Ɓàsàa', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'mas', 'name' => 'Masai',                  'script' => 'Latn', 'native' => 'ɔl-Maa', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'haw', 'name' => 'Hawaiian',               'script' => 'Latn', 'native' => 'ʻŌlelo Hawaiʻi', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'el', 'name' => 'Greek',                  'script' => 'Grek', 'native' => 'Ελληνικά', 'regional' => 'el_GR', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'uz', 'name' => 'Uzbek (Cyrillic)',       'script' => 'Cyrl', 'native' => 'Ўзбек', 'regional' => 'uz_UZ', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'az-Cyrl', 'name' => 'Azerbaijani (Cyrillic)', 'script' => 'Cyrl', 'native' => 'Азәрбајҹан', 'regional' => 'uz_UZ', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'ab', 'name' => 'Abkhazian',              'script' => 'Cyrl', 'native' => 'Аҧсуа', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'os', 'name' => 'Ossetic',                'script' => 'Cyrl', 'native' => 'Ирон', 'regional' => 'os_RU', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'ky', 'name' => 'Kyrgyz',                 'script' => 'Cyrl', 'native' => 'Кыргыз', 'regional' => 'ky_KG', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'sr', 'name' => 'Serbian (Cyrillic)',     'script' => 'Cyrl', 'native' => 'Српски', 'regional' => 'sr_RS', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'av', 'name' => 'Avaric',                 'script' => 'Cyrl', 'native' => 'авар мацӀ', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'ady', 'name' => 'Adyghe',                 'script' => 'Cyrl', 'native' => 'адыгэбзэ', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'ba', 'name' => 'Bashkir',                'script' => 'Cyrl', 'native' => 'башҡорт теле', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'be', 'name' => 'Belarusian',             'script' => 'Cyrl', 'native' => 'беларуская', 'regional' => 'be_BY', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'bg', 'name' => 'Bulgarian',              'script' => 'Cyrl', 'native' => 'български', 'regional' => 'bg_BG', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'kv', 'name' => 'Komi',                   'script' => 'Cyrl', 'native' => 'коми кыв', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'mk', 'name' => 'Macedonian',             'script' => 'Cyrl', 'native' => 'македонски', 'regional' => 'mk_MK', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'mn', 'name' => 'Mongolian (Cyrillic)',   'script' => 'Cyrl', 'native' => 'монгол', 'regional' => 'mn_MN', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'ce', 'name' => 'Chechen',                'script' => 'Cyrl', 'native' => 'нохчийн мотт', 'regional' => 'ce_RU', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'ru', 'name' => 'Russian',                'script' => 'Cyrl', 'native' => 'русский', 'regional' => 'ru_RU', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'sah', 'name' => 'Yakut',                  'script' => 'Cyrl', 'native' => 'саха тыла', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'tt', 'name' => 'Tatar',                  'script' => 'Cyrl', 'native' => 'татар теле', 'regional' => 'tt_RU', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'tg', 'name' => 'Tajik (Cyrillic)',       'script' => 'Cyrl', 'native' => 'тоҷикӣ', 'regional' => 'tg_TJ', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'tk', 'name' => 'Turkmen',                'script' => 'Cyrl', 'native' => 'түркменче', 'regional' => 'tk_TM', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'uk', 'name' => 'Ukrainian',              'script' => 'Cyrl', 'native' => 'українська', 'regional' => 'uk_UA', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'cv', 'name' => 'Chuvash',                'script' => 'Cyrl', 'native' => 'чӑваш чӗлхи', 'regional' => 'cv_RU', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'cu', 'name' => 'Church Slavic',          'script' => 'Cyrl', 'native' => 'ѩзыкъ словѣньскъ', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'kk', 'name' => 'Kazakh',                 'script' => 'Cyrl', 'native' => 'қазақ тілі', 'regional' => 'kk_KZ', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'hy', 'name' => 'Armenian',               'script' => 'Armn', 'native' => 'Հայերեն', 'regional' => 'hy_AM', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'yi', 'name' => 'Yiddish',                'script' => 'Hebr', 'native' => 'ייִדיש', 'regional' => 'yi_US', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'he', 'name' => 'Hebrew',                 'script' => 'Hebr', 'native' => 'עברית', 'regional' => 'he_IL', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'ug', 'name' => 'Uyghur',                 'script' => 'Arab', 'native' => 'ئۇيغۇرچە', 'regional' => 'ug_CN', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'ur', 'name' => 'Urdu',                   'script' => 'Arab', 'native' => 'اردو', 'regional' => 'ur_PK', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
         Language::create(['code' => 'ar', 'name' => 'Arabic',                 'script' => 'Arab', 'native' => 'العربية', 'regional' => 'ar_AE', 'direction' => 'rtl', 'active' => 1, 'country' => '']);
        // Language::create(['code' => 'uz-Arab', 'name' => 'Uzbek (Arabic)',         'script' => 'Arab', 'native' => 'اۉزبېک', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'tg-Arab', 'name' => 'Tajik (Arabic)',         'script' => 'Arab', 'native' => 'تاجیکی', 'regional' => 'tg_TJ', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'sd', 'name' => 'Sindhi',                 'script' => 'Arab', 'native' => 'سنڌي', 'regional' => 'sd_IN', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'fa', 'name' => 'Persian',                'script' => 'Arab', 'native' => 'فارسی', 'regional' => 'fa_IR', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'pa-Arab', 'name' => 'Punjabi (Arabic)',       'script' => 'Arab', 'native' => 'پنجاب', 'regional' => 'pa_IN', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'ps', 'name' => 'Pashto',                 'script' => 'Arab', 'native' => 'پښتو', 'regional' => 'ps_AF', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'ks', 'name' => 'Kashmiri (Arabic)',      'script' => 'Arab', 'native' => 'کأشُر', 'regional' => 'ks_IN', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'ku', 'name' => 'Kurdish',                'script' => 'Arab', 'native' => 'کوردی', 'regional' => 'ku_TR', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'dv', 'name' => 'Divehi',                 'script' => 'Thaa', 'native' => 'ދިވެހިބަސް', 'regional' => 'dv_MV', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'ks-Deva', 'name' => 'Kashmiri (Devaganari)',  'script' => 'Deva', 'native' => 'कॉशुर', 'regional' => 'ks_IN', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'kok', 'name' => 'Konkani',                'script' => 'Deva', 'native' => 'कोंकणी', 'regional' => 'kok_IN', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'doi', 'name' => 'Dogri',                  'script' => 'Deva', 'native' => 'डोगरी', 'regional' => 'doi_IN', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'ne', 'name' => 'Nepali',                 'script' => 'Deva', 'native' => 'नेपाली', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'pra', 'name' => 'Prakrit',                'script' => 'Deva', 'native' => 'प्राकृत', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'brx', 'name' => 'Bodo',                   'script' => 'Deva', 'native' => 'बड़ो', 'regional' => 'brx_IN', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'bra', 'name' => 'Braj',                   'script' => 'Deva', 'native' => 'ब्रज भाषा', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'mr', 'name' => 'Marathi',                'script' => 'Deva', 'native' => 'मराठी', 'regional' => 'mr_IN', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'mai', 'name' => 'Maithili',               'script' => 'Tirh', 'native' => 'मैथिली', 'regional' => 'mai_IN', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'raj', 'name' => 'Rajasthani',             'script' => 'Deva', 'native' => 'राजस्थानी', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'sa', 'name' => 'Sanskrit',               'script' => 'Deva', 'native' => 'संस्कृतम्', 'regional' => 'sa_IN', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'hi', 'name' => 'Hindi',                  'script' => 'Deva', 'native' => 'हिन्दी', 'regional' => 'hi_IN', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'as', 'name' => 'Assamese',               'script' => 'Beng', 'native' => 'অসমীয়া', 'regional' => 'as_IN', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'bn', 'name' => 'Bengali',                'script' => 'Beng', 'native' => 'বাংলা', 'regional' => 'bn_BD', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'mni', 'name' => 'Manipuri',               'script' => 'Beng', 'native' => 'মৈতৈ', 'regional' => 'mni_IN', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'pa', 'name' => 'Punjabi (Gurmukhi)',     'script' => 'Guru', 'native' => 'ਪੰਜਾਬੀ', 'regional' => 'pa_IN', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'gu', 'name' => 'Gujarati',               'script' => 'Gujr', 'native' => 'ગુજરાતી', 'regional' => 'gu_IN', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'or', 'name' => 'Oriya',                  'script' => 'Orya', 'native' => 'ଓଡ଼ିଆ', 'regional' => 'or_IN', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'ta', 'name' => 'Tamil',                  'script' => 'Taml', 'native' => 'தமிழ்', 'regional' => 'ta_IN', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'te', 'name' => 'Telugu',                 'script' => 'Telu', 'native' => 'తెలుగు', 'regional' => 'te_IN', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'kn', 'name' => 'Kannada',                'script' => 'Knda', 'native' => 'ಕನ್ನಡ', 'regional' => 'kn_IN', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'ml', 'name' => 'Malayalam',              'script' => 'Mlym', 'native' => 'മലയാളം', 'regional' => 'ml_IN', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'si', 'name' => 'Sinhala',                'script' => 'Sinh', 'native' => 'සිංහල', 'regional' => 'si_LK', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'th', 'name' => 'Thai',                   'script' => 'Thai', 'native' => 'ไทย', 'regional' => 'th_TH', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'lo', 'name' => 'Lao',                    'script' => 'Laoo', 'native' => 'ລາວ', 'regional' => 'lo_LA', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'bo', 'name' => 'Tibetan',                'script' => 'Tibt', 'native' => 'པོད་སྐད་', 'regional' => 'bo_IN', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'dz', 'name' => 'Dzongkha',               'script' => 'Tibt', 'native' => 'རྫོང་ཁ', 'regional' => 'dz_BT', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'my', 'name' => 'Burmese',                'script' => 'Mymr', 'native' => 'မြန်မာဘာသာ', 'regional' => 'my_MM', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'ka', 'name' => 'Georgian',               'script' => 'Geor', 'native' => 'ქართული', 'regional' => 'ka_GE', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'byn', 'name' => 'Blin',                   'script' => 'Ethi', 'native' => 'ብሊን', 'regional' => 'byn_ER', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'tig', 'name' => 'Tigre',                  'script' => 'Ethi', 'native' => 'ትግረ', 'regional' => 'tig_ER', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'ti', 'name' => 'Tigrinya',               'script' => 'Ethi', 'native' => 'ትግርኛ', 'regional' => 'ti_ET', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'am', 'name' => 'Amharic',                'script' => 'Ethi', 'native' => 'አማርኛ', 'regional' => 'am_ET', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'wal', 'name' => 'Wolaytta',               'script' => 'Ethi', 'native' => 'ወላይታቱ', 'regional' => 'wal_ET', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'chr', 'name' => 'Cherokee',               'script' => 'Cher', 'native' => 'ᏣᎳᎩ', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'iu', 'name' => 'Inuktitut (Canadian Aboriginal Syllabics)', 'script' => 'Cans', 'native' => 'ᐃᓄᒃᑎᑐᑦ', 'regional' => 'iu_CA', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'oj', 'name' => 'Ojibwa',                 'script' => 'Cans', 'native' => 'ᐊᓂᔑᓈᐯᒧᐎᓐ', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'cr', 'name' => 'Cree',                   'script' => 'Cans', 'native' => 'ᓀᐦᐃᔭᐍᐏᐣ', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'km', 'name' => 'Khmer',                  'script' => 'Khmr', 'native' => 'ភាសាខ្មែរ', 'regional' => 'km_KH', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'mn-Mong', 'name' => 'Mongolian (Mongolian)',  'script' => 'Mong', 'native' => 'ᠮᠣᠨᠭᠭᠣᠯ ᠬᠡᠯᠡ', 'regional' => 'mn_MN', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'shi-Tfng', 'name' => 'Tachelhit (Tifinagh)',   'script' => 'Tfng', 'native' => 'ⵜⴰⵎⴰⵣⵉⵖⵜ', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'tzm', 'name' => 'Central Atlas Tamazight (Tifinagh)', 'script' => 'Tfng', 'native' => 'ⵜⴰⵎⴰⵣⵉⵖⵜ', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'yue', 'name' => 'Yue',                    'script' => 'Hant', 'native' => '廣州話', 'regional' => 'yue_HK', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'ja', 'name' => 'Japanese',               'script' => 'Jpan', 'native' => '日本語', 'regional' => 'ja_JP', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'zh', 'name' => 'Chinese (Simplified)',   'script' => 'Hans', 'native' => '简体中文', 'regional' => 'zh_CN', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'zh-Hant', 'name' => 'Chinese (Traditional)',  'script' => 'Hant', 'native' => '繁體中文', 'regional' => 'zh_CN', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'ii', 'name' => 'Sichuan Yi',             'script' => 'Yiii', 'native' => 'ꆈꌠꉙ', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'vai', 'name' => 'Vai (Vai)',              'script' => 'Vaii', 'native' => 'ꕙꔤ', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'jv-Java', 'name' => 'Javanese (Javanese)',    'script' => 'Java', 'native' => 'ꦧꦱꦗꦮ', 'regional' => '', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
        // Language::create(['code' => 'ko', 'name' => 'Korean',                 'script' => 'Hang', 'native' => '한국어', 'regional' => 'ko_KR', 'direction' => 'ltr', 'active' => 0, 'country' => '']);
    }
}
