<?php

// namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Nationalitie;

class NationalitieSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        
        // DB::table('nationalities')->delete();
            //  Nationalitie::create(['name' => 'Afghanistan', 'code' => 'AF']);
            //  Nationalitie::create(['name' => 'Åland Islands', 'code' => 'AX']);
            //  Nationalitie::create(['name' => 'Albania', 'code' => 'AL']);
            //  Nationalitie::create(['name' => 'Algeria', 'code' => 'DZ']);
            //  Nationalitie::create(['name' => 'American Samoa', 'code' => 'AS']);
            //  Nationalitie::create(['name' => 'Andorra', 'code' => 'AD']);
            //  Nationalitie::create(['name' => 'Angola', 'code' => 'AO']);
            //  Nationalitie::create(['name' => 'Anguilla', 'code' => 'AI']);
            //  Nationalitie::create(['name' => 'Antarctica', 'code' => 'AQ']);
            //  Nationalitie::create(['name' => 'Antigua and Barbuda', 'code' => 'AG']);
            //  Nationalitie::create(['name' => 'Argentina', 'code' => 'AR']);
            //  Nationalitie::create(['name' => 'Armenia', 'code' => 'AM']);
            //  Nationalitie::create(['name' => 'Aruba', 'code' => 'AW']);
            //  Nationalitie::create(['name' => 'Australia', 'code' => 'AU']);
            //  Nationalitie::create(['name' => 'Austria', 'code' => 'AT']);
            //  Nationalitie::create(['name' => 'Azerbaijan', 'code' => 'AZ']);
            //  Nationalitie::create(['name' => 'Bahamas', 'code' => 'BS']);
            //  Nationalitie::create(['name' => 'Bahrain', 'code' => 'BH']);
            //  Nationalitie::create(['name' => 'Bangladesh', 'code' => 'BD']);
            //  Nationalitie::create(['name' => 'Barbados', 'code' => 'BB']);
            //  Nationalitie::create(['name' => 'Belarus', 'code' => 'BY']);
            //  Nationalitie::create(['name' => 'Belgium', 'code' => 'BE']);
            //  Nationalitie::create(['name' => 'Belize', 'code' => 'BZ']);
            //  Nationalitie::create(['name' => 'Benin', 'code' => 'BJ']);
            //  Nationalitie::create(['name' => 'Bermuda', 'code' => 'BM']);
            //  Nationalitie::create(['name' => 'Bhutan', 'code' => 'BT']);
            //  Nationalitie::create(['name' => 'Bolivia, Plurinational State of', 'code' => 'BO']);
            //  Nationalitie::create(['name' => 'Bonaire, Sint Eustatius and Saba', 'code' => 'BQ']);
            //  Nationalitie::create(['name' => 'Bosnia and Herzegovina', 'code' => 'BA']);
            //  Nationalitie::create(['name' => 'Botswana', 'code' => 'BW']);
            //  Nationalitie::create(['name' => 'Bouvet Island', 'code' => 'BV']);
            //  Nationalitie::create(['name' => 'Brazil', 'code' => 'BR']);
            //  Nationalitie::create(['name' => 'British Indian Ocean Territory', 'code' => 'IO']);
            //  Nationalitie::create(['name' => 'Brunei Darussalam', 'code' => 'BN']);
            //  Nationalitie::create(['name' => 'Bulgaria', 'code' => 'BG']);
            //  Nationalitie::create(['name' => 'Burkina Faso', 'code' => 'BF']);
            //  Nationalitie::create(['name' => 'Burundi', 'code' => 'BI']);
            //  Nationalitie::create(['name' => 'Cambodia', 'code' => 'KH']);
            //  Nationalitie::create(['name' => 'Cameroon', 'code' => 'CM']);
             Nationalitie::create(['name' => 'Canada', 'code' => 'CA']);
            //  Nationalitie::create(['name' => 'Cape Verde', 'code' => 'CV']);
            //  Nationalitie::create(['name' => 'Cayman Islands', 'code' => 'KY']);
            //  Nationalitie::create(['name' => 'Central African Republic', 'code' => 'CF']);
            //  Nationalitie::create(['name' => 'Chad', 'code' => 'TD']);
            //  Nationalitie::create(['name' => 'Chile', 'code' => 'CL']);
            //  Nationalitie::create(['name' => 'China', 'code' => 'CN']);
            //  Nationalitie::create(['name' => 'Christmas Island', 'code' => 'CX']);
            //  Nationalitie::create(['name' => 'Cocos (Keeling) Islands', 'code' => 'CC']);
            //  Nationalitie::create(['name' => 'Colombia', 'code' => 'CO']);
            //  Nationalitie::create(['name' => 'Comoros', 'code' => 'KM']);
            //  Nationalitie::create(['name' => 'Congo', 'code' => 'CG']);
            //  Nationalitie::create(['name' => 'Congo, the Democratic Republic of the', 'code' => 'CD']);
            //  Nationalitie::create(['name' => 'Cook Islands', 'code' => 'CK']);
            //  Nationalitie::create(['name' => 'Costa Rica', 'code' => 'CR']);
            //  Nationalitie::create(['name' => 'Côte d\'Ivoire', 'code' => 'CI']);
            //  Nationalitie::create(['name' => 'Croatia', 'code' => 'HR']);
            //  Nationalitie::create(['name' => 'Cuba', 'code' => 'CU']);
            //  Nationalitie::create(['name' => 'Curaçao', 'code' => 'CW']);
            //  Nationalitie::create(['name' => 'Cyprus', 'code' => 'CY']);
            //  Nationalitie::create(['name' => 'Czech Republic', 'code' => 'CZ']);
            //  Nationalitie::create(['name' => 'Denmark', 'code' => 'DK']);
            //  Nationalitie::create(['name' => 'Djibouti', 'code' => 'DJ']);
            //  Nationalitie::create(['name' => 'Dominica', 'code' => 'DM']);
            //  Nationalitie::create(['name' => 'Dominican Republic', 'code' => 'DO']);
            //  Nationalitie::create(['name' => 'Ecuador', 'code' => 'EC']);
            //  Nationalitie::create(['name' => 'Egypt', 'code' => 'EG']);
            //  Nationalitie::create(['name' => 'El Salvador', 'code' => 'SV']);
            //  Nationalitie::create(['name' => 'Equatorial Guinea', 'code' => 'GQ']);
            //  Nationalitie::create(['name' => 'Eritrea', 'code' => 'ER']);
            //  Nationalitie::create(['name' => 'Estonia', 'code' => 'EE']);
            //  Nationalitie::create(['name' => 'Ethiopia', 'code' => 'ET']);
            //  Nationalitie::create(['name' => 'Falkland Islands (Malvinas)', 'code' => 'FK']);
            //  Nationalitie::create(['name' => 'Faroe Islands', 'code' => 'FO']);
            //  Nationalitie::create(['name' => 'Fiji', 'code' => 'FJ']);
            //  Nationalitie::create(['name' => 'Finland', 'code' => 'FI']);
            //  Nationalitie::create(['name' => 'France', 'code' => 'FR']);
            //  Nationalitie::create(['name' => 'French Guiana', 'code' => 'GF']);
            //  Nationalitie::create(['name' => 'French Polynesia', 'code' => 'PF']);
            //  Nationalitie::create(['name' => 'French Southern Territories', 'code' => 'TF']);
            //  Nationalitie::create(['name' => 'Gabon', 'code' => 'GA']);
            //  Nationalitie::create(['name' => 'Gambia', 'code' => 'GM']);
            //  Nationalitie::create(['name' => 'Georgia', 'code' => 'GE']);
            //  Nationalitie::create(['name' => 'Germany', 'code' => 'DE']);
            //  Nationalitie::create(['name' => 'Ghana', 'code' => 'GH']);
            //  Nationalitie::create(['name' => 'Gibraltar', 'code' => 'GI']);
            //  Nationalitie::create(['name' => 'Greece', 'code' => 'GR']);
            //  Nationalitie::create(['name' => 'Greenland', 'code' => 'GL']);
            //  Nationalitie::create(['name' => 'Grenada', 'code' => 'GD']);
            //  Nationalitie::create(['name' => 'Guadeloupe', 'code' => 'GP']);
            //  Nationalitie::create(['name' => 'Guam', 'code' => 'GU']);
            //  Nationalitie::create(['name' => 'Guatemala', 'code' => 'GT']);
            //  Nationalitie::create(['name' => 'Guernsey', 'code' => 'GG']);
            //  Nationalitie::create(['name' => 'Guinea', 'code' => 'GN']);
            //  Nationalitie::create(['name' => 'Guinea-Bissau', 'code' => 'GW']);
            //  Nationalitie::create(['name' => 'Guyana', 'code' => 'GY']);
            //  Nationalitie::create(['name' => 'Haiti', 'code' => 'HT']);
            //  Nationalitie::create(['name' => 'Heard Island and McDonald Mcdonald Islands', 'code' => 'HM']);
            //  Nationalitie::create(['name' => 'Holy See (Vatican City State)', 'code' => 'VA']);
            //  Nationalitie::create(['name' => 'Honduras', 'code' => 'HN']);
            //  Nationalitie::create(['name' => 'Hong Kong', 'code' => 'HK']);
            //  Nationalitie::create(['name' => 'Hungary', 'code' => 'HU']);
            //  Nationalitie::create(['name' => 'Iceland', 'code' => 'IS']);
            //  Nationalitie::create(['name' => 'India', 'code' => 'IN']);
            //  Nationalitie::create(['name' => 'Indonesia', 'code' => 'ID']);
             Nationalitie::create(['name' => 'Iran, Islamic Republic of', 'code' => 'IR']);
            //  Nationalitie::create(['name' => 'Iraq', 'code' => 'IQ']);
            //  Nationalitie::create(['name' => 'Ireland', 'code' => 'IE']);
            //  Nationalitie::create(['name' => 'Isle of Man', 'code' => 'IM']);
            //  Nationalitie::create(['name' => 'Israel', 'code' => 'IL']);
            //  Nationalitie::create(['name' => 'Italy', 'code' => 'IT']);
            //  Nationalitie::create(['name' => 'Jamaica', 'code' => 'JM']);
            //  Nationalitie::create(['name' => 'Japan', 'code' => 'JP']);
            //  Nationalitie::create(['name' => 'Jersey', 'code' => 'JE']);
            //  Nationalitie::create(['name' => 'Jordan', 'code' => 'JO']);
            //  Nationalitie::create(['name' => 'Kazakhstan', 'code' => 'KZ']);
            //  Nationalitie::create(['name' => 'Kenya', 'code' => 'KE']);
            //  Nationalitie::create(['name' => 'Kiribati', 'code' => 'KI']);
            //  Nationalitie::create(['name' => 'Korea, Democratic People\'s Republic of', 'code' => 'KP']);
            //  Nationalitie::create(['name' => 'Korea, Republic of', 'code' => 'KR']);
            //  Nationalitie::create(['name' => 'Kuwait', 'code' => 'KW']);
            //  Nationalitie::create(['name' => 'Kyrgyzstan', 'code' => 'KG']);
            //  Nationalitie::create(['name' => 'Lao People\'s Democratic Republic', 'code' => 'LA']);
            //  Nationalitie::create(['name' => 'Latvia', 'code' => 'LV']);
             Nationalitie::create(['name' => 'Lebanon', 'code' => 'LB']);
            //  Nationalitie::create(['name' => 'Lesotho', 'code' => 'LS']);
            //  Nationalitie::create(['name' => 'Liberia', 'code' => 'LR']);
            //  Nationalitie::create(['name' => 'Libya', 'code' => 'LY']);
            //  Nationalitie::create(['name' => 'Liechtenstein', 'code' => 'LI']);
            //  Nationalitie::create(['name' => 'Lithuania', 'code' => 'LT']);
            //  Nationalitie::create(['name' => 'Luxembourg', 'code' => 'LU']);
            //  Nationalitie::create(['name' => 'Macao', 'code' => 'MO']);
            //  Nationalitie::create(['name' => 'Macedonia, the Former Yugoslav Republic of', 'code' => 'MK']);
            //  Nationalitie::create(['name' => 'Madagascar', 'code' => 'MG']);
            //  Nationalitie::create(['name' => 'Malawi', 'code' => 'MW']);
            //  Nationalitie::create(['name' => 'Malaysia', 'code' => 'MY']);
            //  Nationalitie::create(['name' => 'Maldives', 'code' => 'MV']);
            //  Nationalitie::create(['name' => 'Mali', 'code' => 'ML']);
            //  Nationalitie::create(['name' => 'Malta', 'code' => 'MT']);
            //  Nationalitie::create(['name' => 'Marshall Islands', 'code' => 'MH']);
            //  Nationalitie::create(['name' => 'Martinique', 'code' => 'MQ']);
            //  Nationalitie::create(['name' => 'Mauritania', 'code' => 'MR']);
            //  Nationalitie::create(['name' => 'Mauritius', 'code' => 'MU']);
            //  Nationalitie::create(['name' => 'Mayotte', 'code' => 'YT']);
            //  Nationalitie::create(['name' => 'Mexico', 'code' => 'MX']);
            //  Nationalitie::create(['name' => 'Micronesia, Federated States of', 'code' => 'FM']);
            //  Nationalitie::create(['name' => 'Moldova, Republic of', 'code' => 'MD']);
            //  Nationalitie::create(['name' => 'Monaco', 'code' => 'MC']);
            //  Nationalitie::create(['name' => 'Mongolia', 'code' => 'MN']);
            //  Nationalitie::create(['name' => 'Montenegro', 'code' => 'ME']);
            //  Nationalitie::create(['name' => 'Montserrat', 'code' => 'MS']);
            //  Nationalitie::create(['name' => 'Morocco', 'code' => 'MA']);
            //  Nationalitie::create(['name' => 'Mozambique', 'code' => 'MZ']);
            //  Nationalitie::create(['name' => 'Myanmar', 'code' => 'MM']);
            //  Nationalitie::create(['name' => 'Namibia', 'code' => 'NA']);
            //  Nationalitie::create(['name' => 'Nauru', 'code' => 'NR']);
            //  Nationalitie::create(['name' => 'Nepal', 'code' => 'NP']);
            //  Nationalitie::create(['name' => 'Netherlands', 'code' => 'NL']);
            //  Nationalitie::create(['name' => 'New Caledonia', 'code' => 'NC']);
            //  Nationalitie::create(['name' => 'New Zealand', 'code' => 'NZ']);
            //  Nationalitie::create(['name' => 'Nicaragua', 'code' => 'NI']);
            //  Nationalitie::create(['name' => 'Niger', 'code' => 'NE']);
            //  Nationalitie::create(['name' => 'Nigeria', 'code' => 'NG']);
            //  Nationalitie::create(['name' => 'Niue', 'code' => 'NU']);
            //  Nationalitie::create(['name' => 'Norfolk Island', 'code' => 'NF']);
            //  Nationalitie::create(['name' => 'Northern Mariana Islands', 'code' => 'MP']);
            //  Nationalitie::create(['name' => 'Norway', 'code' => 'NO']);
            //  Nationalitie::create(['name' => 'Oman', 'code' => 'OM']);
            //  Nationalitie::create(['name' => 'Pakistan', 'code' => 'PK']);
            //  Nationalitie::create(['name' => 'Palau', 'code' => 'PW']);
            //  Nationalitie::create(['name' => 'Palestine, State of', 'code' => 'PS']);
            //  Nationalitie::create(['name' => 'Panama', 'code' => 'PA']);
            //  Nationalitie::create(['name' => 'Papua New Guinea', 'code' => 'PG']);
            //  Nationalitie::create(['name' => 'Paraguay', 'code' => 'PY']);
            //  Nationalitie::create(['name' => 'Peru', 'code' => 'PE']);
            //  Nationalitie::create(['name' => 'Philippines', 'code' => 'PH']);
            //  Nationalitie::create(['name' => 'Pitcairn', 'code' => 'PN']);
            //  Nationalitie::create(['name' => 'Poland', 'code' => 'PL']);
            //  Nationalitie::create(['name' => 'Portugal', 'code' => 'PT']);
            //  Nationalitie::create(['name' => 'Puerto Rico', 'code' => 'PR']);
            //  Nationalitie::create(['name' => 'Qatar', 'code' => 'QA']);
            //  Nationalitie::create(['name' => 'Réunion', 'code' => 'RE']);
            //  Nationalitie::create(['name' => 'Romania', 'code' => 'RO']);
            //  Nationalitie::create(['name' => 'Russian Federation', 'code' => 'RU']);
            //  Nationalitie::create(['name' => 'Rwanda', 'code' => 'RW']);
            //  Nationalitie::create(['name' => 'Saint Barthélemy', 'code' => 'BL']);
            //  Nationalitie::create(['name' => 'Saint Helena, Ascension and Tristan da Cunha', 'code' => 'SH']);
            //  Nationalitie::create(['name' => 'Saint Kitts and Nevis', 'code' => 'KN']);
            //  Nationalitie::create(['name' => 'Saint Lucia', 'code' => 'LC']);
            //  Nationalitie::create(['name' => 'Saint Martin (French part)', 'code' => 'MF']);
            //  Nationalitie::create(['name' => 'Saint Pierre and Miquelon', 'code' => 'PM']);
            //  Nationalitie::create(['name' => 'Saint Vincent and the Grenadines', 'code' => 'VC']);
            //  Nationalitie::create(['name' => 'Samoa', 'code' => 'WS']);
            //  Nationalitie::create(['name' => 'San Marino', 'code' => 'SM']);
            //  Nationalitie::create(['name' => 'Sao Tome and Principe', 'code' => 'ST']);
            //  Nationalitie::create(['name' => 'Saudi Arabia', 'code' => 'SA']);
            //  Nationalitie::create(['name' => 'Senegal', 'code' => 'SN']);
            //  Nationalitie::create(['name' => 'Serbia', 'code' => 'RS']);
            //  Nationalitie::create(['name' => 'Seychelles', 'code' => 'SC']);
            //  Nationalitie::create(['name' => 'Sierra Leone', 'code' => 'SL']);
            //  Nationalitie::create(['name' => 'Singapore', 'code' => 'SG']);
            //  Nationalitie::create(['name' => 'Sint Maarten (Dutch part)', 'code' => 'SX']);
            //  Nationalitie::create(['name' => 'Slovakia', 'code' => 'SK']);
            //  Nationalitie::create(['name' => 'Slovenia', 'code' => 'SI']);
            //  Nationalitie::create(['name' => 'Solomon Islands', 'code' => 'SB']);
            //  Nationalitie::create(['name' => 'Somalia', 'code' => 'SO']);
            //  Nationalitie::create(['name' => 'South Africa', 'code' => 'ZA']);
            //  Nationalitie::create(['name' => 'South Georgia and the South Sandwich Islands', 'code' => 'GS']);
            //  Nationalitie::create(['name' => 'South Sudan', 'code' => 'SS']);
            //  Nationalitie::create(['name' => 'Spain', 'code' => 'ES']);
            //  Nationalitie::create(['name' => 'Sri Lanka', 'code' => 'LK']);
            //  Nationalitie::create(['name' => 'Sudan', 'code' => 'SD']);
            //  Nationalitie::create(['name' => 'Suriname', 'code' => 'SR']);
            //  Nationalitie::create(['name' => 'Svalbard and Jan Mayen', 'code' => 'SJ']);
            //  Nationalitie::create(['name' => 'Swaziland', 'code' => 'SZ']);
            //  Nationalitie::create(['name' => 'Sweden', 'code' => 'SE']);
            //  Nationalitie::create(['name' => 'Switzerland', 'code' => 'CH']);
             Nationalitie::create(['name' => 'Syrian Arab Republic', 'code' => 'SY']);
            //  Nationalitie::create(['name' => 'Taiwan', 'code' => 'TW']);
            //  Nationalitie::create(['name' => 'Tajikistan', 'code' => 'TJ']);
            //  Nationalitie::create(['name' => 'Tanzania, United Republic of', 'code' => 'TZ']);
            //  Nationalitie::create(['name' => 'Thailand', 'code' => 'TH']);
            //  Nationalitie::create(['name' => 'Timor-Leste', 'code' => 'TL']);
            //  Nationalitie::create(['name' => 'Togo', 'code' => 'TG']);
            //  Nationalitie::create(['name' => 'Tokelau', 'code' => 'TK']);
            //  Nationalitie::create(['name' => 'Tonga', 'code' => 'TO']);
            //  Nationalitie::create(['name' => 'Trinidad and Tobago', 'code' => 'TT']);
            //  Nationalitie::create(['name' => 'Tunisia', 'code' => 'TN']);
            //  Nationalitie::create(['name' => 'Turkey', 'code' => 'TR']);
            //  Nationalitie::create(['name' => 'Turkmenistan', 'code' => 'TM']);
            //  Nationalitie::create(['name' => 'Turks and Caicos Islands', 'code' => 'TC']);
            //  Nationalitie::create(['name' => 'Tuvalu', 'code' => 'TV']);
            //  Nationalitie::create(['name' => 'Uganda', 'code' => 'UG']);
            //  Nationalitie::create(['name' => 'Ukraine', 'code' => 'UA']);
            //  Nationalitie::create(['name' => 'United Arab Emirates', 'code' => 'AE']);
            //  Nationalitie::create(['name' => 'United Kingdom', 'code' => 'GB']);
            //  Nationalitie::create(['name' => 'United States', 'code' => 'US']);
            //  Nationalitie::create(['name' => 'United States Minor Outlying Islands', 'code' => 'UM']);
            //  Nationalitie::create(['name' => 'Uruguay', 'code' => 'UY']);
            //  Nationalitie::create(['name' => 'Uzbekistan', 'code' => 'UZ']);
            //  Nationalitie::create(['name' => 'Vanuatu', 'code' => 'VU']);
            //  Nationalitie::create(['name' => 'Venezuela, Bolivarian Republic of', 'code' => 'VE']);
            //  Nationalitie::create(['name' => 'Viet Nam', 'code' => 'VN']);
            //  Nationalitie::create(['name' => 'Virgin Islands, British', 'code' => 'VG']);
            //  Nationalitie::create(['name' => 'Virgin Islands, U.S.', 'code' => 'VI']);
            //  Nationalitie::create(['name' => 'Wallis and Futuna', 'code' => 'WF']);
            //  Nationalitie::create(['name' => 'Western Sahara', 'code' => 'EH']);
            //  Nationalitie::create(['name' => 'Yemen', 'code' => 'YE']);
            //  Nationalitie::create(['name' => 'Zambia', 'code' => 'ZM']);
            //  Nationalitie::create(['name' => 'Zimbabwe', 'code' => 'ZW']);

    }
}
